name: "[PR] LWC tests and formatting"
on:
  pull_request:
    branches:
      - '*'

jobs:
  lwc-validation:
    name: Jest tests and Prettier check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run prettier:check
